import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/auth";
import { Toaster } from "./components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} flex flex-col items-center`}>
        <main className="container p-0 max-w-5xl flex flex-col">
          <AuthProvider>
            {children}
            <Toaster />
            {/* <Footer /> */}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
